/**
 * Media registry. Every file referenced here is generated by `npm run media`
 * from the original uploads (which stay untouched at the repository root).
 */

export type ImageAsset = {
  /** Path prefix without width or extension, e.g. `/media/images/impactx-key-visual`. */
  base: string;
  /** Rendition widths available as AVIF and WebP. The largest also exists as JPEG. */
  widths: readonly number[];
  /** Intrinsic size of the largest rendition (used for aspect ratio, prevents layout shift). */
  width: number;
  height: number;
  alt: string;
  /** CSS object-position used when the image is cropped, e.g. "50% 0%" to keep the top. */
  focus?: string;
};

export type FilmAsset = {
  id: string;
  title: string;
  /** Full film with sound (byte-identical copy of the original upload). */
  src: string;
  /** Short silent loop used for previews. */
  teaser: string;
  /** First frame of the teaser, so previews start without a visual jump. */
  teaserPoster: ImageAsset;
  /** Poster frame supplied with the film. */
  poster: ImageAsset;
  /** Seconds. */
  duration: number;
  width: number;
  height: number;
};

const poster = (name: string, alt: string): ImageAsset => ({
  base: `/media/images/${name}`,
  widths: [440, 880],
  width: 880,
  height: 1168,
  alt,
});

const frame = (name: string, alt: string): ImageAsset => ({
  base: `/media/images/${name}`,
  widths: [240, 480],
  width: 480,
  height: 854,
  alt,
});

/** Social posts from the skincare series, 4:5 portrait. */
const socialPost = (name: string, alt: string): ImageAsset => ({
  base: `/media/images/${name}`,
  widths: [540, 1080, 1620],
  width: 1620,
  height: 2025,
  alt,
});

/** Frames from the 1080×1920 serum films, which also come in a sharper 960 size. */
const frameHD = (name: string, alt: string): ImageAsset => ({
  base: `/media/images/${name}`,
  widths: [240, 480, 960],
  width: 960,
  height: 1707,
  alt,
});

export function imageUrl(image: ImageAsset, format: "avif" | "webp" | "jpg" = "jpg", width?: number) {
  const w = width ?? Math.max(...image.widths);
  return `${image.base}-${w}.${format}`;
}

export const images = {
  keyVisual: poster(
    "impactx-key-visual",
    "ImpactX poster with the headline “Your ads aren’t failing. Your ideas are.” The red-haired mascot in dark glasses leans over a desk, the Burj Khalifa lit up behind.",
  ),
  aiVideoA: poster(
    "impactx-ai-video-a",
    "ImpactX poster “30 days of content. Zero cameras.” The mascot reaches for glowing vertical video frames: a watch, a sports car in Dubai, fashion, fitness and food.",
  ),
  aiVideoB: poster(
    "impactx-ai-video-b",
    "Lifestyle variant of the “30 days of content” poster, with frames reading “Stronger today”, “Better moments”, “Bigger dreams”, “Bolder styles” and “New places”.",
  ),
  automationA: poster(
    "impactx-automation-a",
    "ImpactX poster “Your business doesn’t sleep. Why does your marketing?” A glass interface shows a restaurant booking handled automatically between 22:47 and 22:50.",
  ),
  automationB: poster(
    "impactx-automation-b",
    "Simplified variant of the automation poster: incoming message, replied automatically, booking confirmed, follow-up sent, running 24/7.",
  ),
};

export const social = {
  beeslineA: socialPost(
    "social-beesline-a",
    "Beesline post: three serums in yellow, blue and orange float in honey-gold light with honeycomb and honey drops, under the headline “Liquid Gold, Three Ways.”",
  ),
  beeslineB: socialPost(
    "social-beesline-b",
    "Beesline post: the orange, blue and yellow serums stand on colour-matched steps, each under its skin concern, below the headline “What’s Your Skin Concern?”",
  ),
  lrpA: socialPost(
    "social-lrp-a",
    "La Roche-Posay post: the Anthelios UVMune 400 fluid on a white plinth in a beam of sunlight, under the headline “Protection, all the way to 400nm.” and a UV spectrum bar.",
  ),
  lrpB: socialPost(
    "social-lrp-b",
    "La Roche-Posay post: a woman in a white swimsuit holds the Anthelios bottle against a deep blue sky, beside the headline “Sun’s out. Shield up.”",
  ),
  biodermaA: socialPost(
    "social-bioderma-a",
    "Bioderma post: the Photoderm XDefense bottle floats inside a clear sphere with a yellow glow, under the headline “Defense, down to the cell.”",
  ),
  biodermaB: socialPost(
    "social-bioderma-b",
    "Bioderma post: the Photoderm XDefense bottle lies on a navy and white striped beach towel beside yellow sunglasses, under the headline “Salt. Sun. Shielded.”",
  ),
};

export const films = {
  brand: {
    id: "brand-film",
    title: "ImpactX Brand Film",
    src: "/media/videos/brand-film.mp4",
    teaser: "/media/videos/brand-film-teaser.mp4",
    teaserPoster: frame("brand-film-teaser-poster", "Close-up of the ImpactX mascot, lit by red neon."),
    poster: frame("brand-film-poster", "A business owner holds up his phone showing a post from his clothing store."),
    duration: 50,
    width: 478,
    height: 850,
  },
  skincare: {
    id: "skincare-film",
    title: "Skincare Launch Ad",
    src: "/media/videos/skincare-film.mp4",
    teaser: "/media/videos/skincare-film-teaser.mp4",
    teaserPoster: frame("skincare-film-teaser-poster", "A blue skincare pack of 24 blemish patches on a white studio set."),
    poster: frame("skincare-film-poster", "A blue skincare pack of 24 blemish patches on a white studio set."),
    duration: 26,
    width: 480,
    height: 854,
  },
  serumReel: {
    id: "serum-reel",
    title: "Serum Launch Reel",
    src: "/media/videos/serum-reel.mp4",
    teaser: "/media/videos/serum-reel-teaser.mp4",
    // The teaser is 720 wide, so its first frame is 480×853.
    teaserPoster: {
      ...frame("serum-reel-teaser-poster", "A white serum bottle with a silver dropper cap floats on a deep blue set under the title “Age Proteom™”."),
      height: 853,
    },
    poster: frameHD(
      "serum-reel-poster",
      "A white serum bottle with a silver dropper cap floats on a deep blue set, light flaring across the cap, under the title “Age Proteom™, patented biotechnology”.",
    ),
    duration: 20,
    width: 1080,
    height: 1920,
  },
  serumIngredients: {
    id: "serum-ingredients",
    title: "Serum Ingredient Film",
    src: "/media/videos/serum-ingredients.mp4",
    teaser: "/media/videos/serum-ingredients-teaser.mp4",
    teaserPoster: {
      ...frame("serum-ingredients-teaser-poster", "Rows of white serum bottles with silver dropper caps on a warm stone surface."),
      height: 853,
    },
    poster: frameHD(
      "serum-ingredients-poster",
      "The serum bottle on a stone plinth in warm light, under the callout “Cellular Water, patented: mimics the water in our skin cells”.",
    ),
    duration: 15,
    width: 1080,
    height: 1920,
  },
} satisfies Record<string, FilmAsset>;

export const stills = {
  brand: [
    frame("brand-film-still-1", "A frustrated business owner shows a post from his clothing store on his phone."),
    frame("brand-film-still-2", "The owner holds his head in his hands as the mascot appears behind him."),
    frame("brand-film-still-3", "Close-up of the mascot, lit by red neon."),
    frame("brand-film-still-4", "Neon signs list the services: strategy, content, media buying, AI automation, AI video, growth."),
    frame("brand-film-still-5", "A glass screen shows an automated chat conversation next to the mascot."),
    frame("brand-film-still-6", "The mascot stands in front of a wall of AI-generated video content."),
    frame("brand-film-still-7", "The mascot presses a package card on the desk, the Dubai skyline behind."),
  ],
  skincare: [
    frame("skincare-film-still-1", "Macro shot of a clear hydrocolloid patch on a fingertip."),
    frame("skincare-film-still-2", "The red Original pack on a white studio set."),
    frame("skincare-film-still-3", "The blue Invisible+ pack on a white studio set."),
    frame("skincare-film-still-4", "The orange Face pack with patches in the foreground."),
    { ...frame("skincare-film-still-5", "The full range of three packs under the line “Your blemish hero”."), focus: "50% 0%" },
  ],
  serumReel: [
    frameHD("serum-reel-still-1", "The serum bottle floats at an angle as a pink light flare crosses its silver cap."),
    frameHD("serum-reel-still-2", "Close-up of the bottle’s silver cap and label."),
    {
      ...frameHD("serum-reel-still-3", "The dropper releases a drop into the open bottle, beside the claim “83% firmer skin”."),
      focus: "50% 20%",
    },
    frameHD("serum-reel-still-4", "A drop falls from the dropper into the bottle, beside the claim “87% more radiant skin”."),
    frameHD("serum-reel-still-5", "A pearl of serum sits on the bottle’s neck, beside the claim “83% smoother fine lines”."),
    frameHD("serum-reel-still-6", "The bottle on a glowing pedestal under the line “The cell longevity serum”, with the parent company’s logo below."),
  ],
  serumIngredients: [
    frameHD("serum-ingredients-still-1", "Rows of identical serum bottles stretch into the distance, one in sharp focus at the centre."),
    frameHD("serum-ingredients-still-2", "Macro of the bottle’s base and its signature line, “Care first.”"),
    frameHD("serum-ingredients-still-3", "Macro of white serum flowing from the dropper into the neck of the bottle."),
    frameHD(
      "serum-ingredients-still-4",
      "The bottle on a stone plinth in a burst of fine powder, under the callout: patented snow-bacteria extract that protects skin proteins from carbonylation.",
    ),
    frameHD("serum-ingredients-still-5", "The bottle under the callout “Cellular Water, patented: mimics the water in our skin cells”."),
    frameHD(
      "serum-ingredients-still-6",
      "The bottle under the callout listing the rest of the formula: sodium acetylated hyaluronate, adenosine, glycerin and tocopherol.",
    ),
    frameHD("serum-ingredients-still-7", "End card with the product name above the bottle and the parent company’s logo below."),
  ],
};
