/**
 * Media registry. Every file referenced here is generated by `npm run media`
 * from the original uploads (which stay untouched at the repository root).
 */

export type ImageAsset = {
  /** Path prefix without width or extension, e.g. `/media/images/impactx-key-visual`. */
  base: string;
  /** Rendition widths available as AVIF and WebP. The largest also exists as JPEG. */
  widths: readonly number[];
  /** Intrinsic size of the largest rendition (used for aspect ratio, prevents layout shift). */
  width: number;
  height: number;
  alt: string;
};

export type FilmAsset = {
  id: string;
  title: string;
  /** Full film with sound (byte-identical copy of the original upload). */
  src: string;
  /** Short silent loop used for previews. */
  teaser: string;
  /** First frame of the teaser, so previews start without a visual jump. */
  teaserPoster: ImageAsset;
  /** Poster frame supplied with the film. */
  poster: ImageAsset;
  /** Seconds. */
  duration: number;
  width: number;
  height: number;
};

const poster = (name: string, alt: string): ImageAsset => ({
  base: `/media/images/${name}`,
  widths: [440, 880],
  width: 880,
  height: 1168,
  alt,
});

const frame = (name: string, alt: string): ImageAsset => ({
  base: `/media/images/${name}`,
  widths: [240, 480],
  width: 480,
  height: 854,
  alt,
});

export function imageUrl(image: ImageAsset, format: "avif" | "webp" | "jpg" = "jpg", width?: number) {
  const w = width ?? Math.max(...image.widths);
  return `${image.base}-${w}.${format}`;
}

export const images = {
  keyVisual: poster(
    "impactx-key-visual",
    "ImpactX poster with the headline “Your ads aren’t failing. Your ideas are.” The red-haired mascot in dark glasses leans over a desk, the Burj Khalifa lit up behind.",
  ),
  aiVideoA: poster(
    "impactx-ai-video-a",
    "ImpactX poster “30 days of content. Zero cameras.” The mascot reaches for glowing vertical video frames: a watch, a sports car in Dubai, fashion, fitness and food.",
  ),
  aiVideoB: poster(
    "impactx-ai-video-b",
    "Lifestyle variant of the “30 days of content” poster, with frames reading “Stronger today”, “Better moments”, “Bigger dreams”, “Bolder styles” and “New places”.",
  ),
  automationA: poster(
    "impactx-automation-a",
    "ImpactX poster “Your business doesn’t sleep. Why does your marketing?” A glass interface shows a restaurant booking handled automatically between 22:47 and 22:50.",
  ),
  automationB: poster(
    "impactx-automation-b",
    "Simplified variant of the automation poster: incoming message, replied automatically, booking confirmed, follow-up sent, running 24/7.",
  ),
};

export const films = {
  brand: {
    id: "brand-film",
    title: "ImpactX Brand Film",
    src: "/media/videos/brand-film.mp4",
    teaser: "/media/videos/brand-film-teaser.mp4",
    teaserPoster: frame("brand-film-teaser-poster", "Close-up of the ImpactX mascot, lit by red neon."),
    poster: frame("brand-film-poster", "A business owner holds up his phone showing a post from his clothing store."),
    duration: 50,
    width: 480,
    height: 854,
  },
  skincare: {
    id: "skincare-film",
    title: "Skincare Launch Ad",
    src: "/media/videos/skincare-film.mp4",
    teaser: "/media/videos/skincare-film-teaser.mp4",
    teaserPoster: frame("skincare-film-teaser-poster", "A blue skincare pack of 24 blemish patches on a white studio set."),
    poster: frame("skincare-film-poster", "A blue skincare pack of 24 blemish patches on a white studio set."),
    duration: 26,
    width: 480,
    height: 854,
  },
} satisfies Record<string, FilmAsset>;

export const stills = {
  brand: [
    frame("brand-film-still-1", "A frustrated business owner shows a post from his clothing store on his phone."),
    frame("brand-film-still-2", "The owner holds his head in his hands as the mascot appears behind him."),
    frame("brand-film-still-3", "Close-up of the mascot, lit by red neon."),
    frame("brand-film-still-4", "Neon signs list the services: strategy, content, media buying, AI automation, AI video, growth."),
    frame("brand-film-still-5", "A glass screen shows an automated chat conversation next to the mascot."),
    frame("brand-film-still-6", "The mascot stands in front of a wall of AI-generated video content."),
    frame("brand-film-still-7", "The mascot presses a package card on the desk, the Dubai skyline behind."),
  ],
  skincare: [
    frame("skincare-film-still-1", "Macro shot of a clear hydrocolloid patch on a fingertip."),
    frame("skincare-film-still-2", "The red Original pack on a white studio set."),
    frame("skincare-film-still-3", "The blue Invisible+ pack on a white studio set."),
    frame("skincare-film-still-4", "The orange Face pack with patches in the foreground."),
    frame("skincare-film-still-5", "The full range of three packs under the line “Your blemish hero”."),
  ],
};
